services:
  backend:
    build:
      context: ./RoveriBack_final   # ⬅️ Nome certo
    container_name: roveri_backend
    command: >
      sh -c "python manage.py migrate &&
        daphne -b 0.0.0.0 -p 8000 project.asgi:application"
    volumes:
      - ./RoveriBack_final:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - pgbouncer
      - redis
    environment:
      - POSTGRES_DB=roveri_db
      - POSTGRES_USER=roveri_user
      - POSTGRES_PASSWORD=roveri_pass
      - DB_HOST=db
      - DB_PORT=5432
      - "DATABASE_URL=postgresql://neondb_owner:npg_5JI3FTnDRbHf@ep-proud-shadow-acuv6914-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      - DB_SSL=require
      - DJANGO_SETTINGS_MODULE=project.settings

  frontend:
    build:
      context: ./Roveri_final
    container_name: roveri_frontend
    volumes:
      - ./Roveri_final:/app:cached
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000/api


  db:
    image: postgres:15
    container_name: roveri_db
    restart: always
    environment:
      POSTGRES_DB: roveri_db
      POSTGRES_USER: roveri_user
      POSTGRES_PASSWORD: roveri_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: roveri_pgbouncer
    restart: always
    volumes:
      - ./pgbouncer:/etc/pgbouncer:ro
    ports:
      - "6432:6432"
    depends_on:
      - db

  redis:
    image: redis:7
    container_name: roveri_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  frontend_node_modules:
